const JSON_HEADERS={"content-type":"application/json; charset=utf-8"};
const CORS={"access-control-allow-origin":"https://gyeongjin-family-app.pages.dev","access-control-allow-methods":"GET,POST,PUT,OPTIONS","access-control-allow-headers":"authorization,content-type","vary":"Origin"};
const enc=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...CORS}});
const id=()=>crypto.randomUUID();
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
async function digest(v){return hex(await crypto.subtle.digest("SHA-256",enc.encode(v)))}
async function passwordHash(password,salt){let data=enc.encode(password+":"+salt);for(let i=0;i<120000;i++)data=new Uint8Array(await crypto.subtle.digest("SHA-256",data));return hex(data)}
async function body(req){try{return await req.json()}catch{return {}}}
async function auth(req,env){const raw=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!raw)return null;const h=await digest(raw);return env.DB.prepare(`SELECT m.id,m.family_id,m.name,m.role,m.is_admin,m.emoji FROM sessions s JOIN members m ON m.id=s.member_id WHERE s.token_hash=? AND s.expires_at>datetime('now')`).bind(h).first()}
async function createSession(memberId,env){const token=crypto.randomUUID()+crypto.randomUUID();const tokenHash=await digest(token);await env.DB.prepare("INSERT INTO sessions(token_hash,member_id,expires_at) VALUES(?,?,datetime('now','+30 days'))").bind(tokenHash,memberId).run();return token}
export default {async fetch(req,env){const url=new URL(req.url);
if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(url.pathname==="/api/health")return json({ok:true,service:"gyeongjin-family-api"});
if(url.pathname==="/api/setup-status"&&req.method==="GET"){const row=await env.DB.prepare("SELECT COUNT(*) c FROM families").first();return json({initialized:Number(row?.c||0)>0})}
if(url.pathname==="/api/setup"&&req.method==="POST"){const b=await body(req);if(!b.familyName||!b.parentName||!b.password||b.password.length<4)return json({error:"가족명, 부모 이름, 4자 이상 비밀번호가 필요합니다."},400);const exists=await env.DB.prepare("SELECT COUNT(*) c FROM families").first();if(Number(exists?.c||0)>0)return json({error:"초기 가족 설정이 이미 완료되었습니다."},409);const familyId=id(),memberId=id(),salt=id(),hash=await passwordHash(b.password,salt);await env.DB.batch([env.DB.prepare("INSERT INTO families(id,name) VALUES(?,?)").bind(familyId,b.familyName),env.DB.prepare("INSERT INTO members(id,family_id,name,role,is_admin,emoji,password_hash,password_salt) VALUES(?,?,?,?,1,?,?,?)").bind(memberId,familyId,b.parentName,"parent",b.emoji||"🙂",hash,salt)]);const token=await createSession(memberId,env);return json({token,member:{id:memberId,name:b.parentName,role:"parent",isAdmin:true,emoji:b.emoji||"🙂"}})}
if(url.pathname==="/api/login"&&req.method==="POST"){const b=await body(req);const m=await env.DB.prepare("SELECT * FROM members WHERE name=? LIMIT 1").bind(b.name||"").first();if(!m||await passwordHash(b.password||"",m.password_salt)!==m.password_hash)return json({error:"이름 또는 비밀번호를 확인해주세요."},401);const token=await createSession(m.id,env);return json({token,member:{id:m.id,name:m.name,role:m.role,isAdmin:!!m.is_admin,emoji:m.emoji}})}
const me=await auth(req,env);if(!me)return json({error:"로그인이 필요합니다."},401);
if(url.pathname==="/api/me")return json({member:{id:me.id,name:me.name,role:me.role,isAdmin:!!me.is_admin,emoji:me.emoji}});
if(url.pathname==="/api/members"&&req.method==="GET"){const rows=await env.DB.prepare("SELECT id,name,role,is_admin,emoji,created_at FROM members WHERE family_id=? ORDER BY created_at").bind(me.family_id).all();return json({members:(rows.results||[]).map(m=>({id:m.id,name:m.name,role:m.role,isAdmin:!!m.is_admin,emoji:m.emoji}))})}
if(url.pathname==="/api/members"&&req.method==="POST"){if(!me.is_admin)return json({error:"관리자만 가족을 등록할 수 있습니다."},403);const b=await body(req);if(!b.name||!b.password||b.password.length<4||!["parent","child"].includes(b.role))return json({error:"이름, 역할, 4자 이상 비밀번호가 필요합니다."},400);const memberId=id(),salt=id(),hash=await passwordHash(b.password,salt);try{await env.DB.prepare("INSERT INTO members(id,family_id,name,role,is_admin,emoji,password_hash,password_salt) VALUES(?,?,?,?,?,?,?,?)").bind(memberId,me.family_id,b.name,b.role,b.role==="parent"?1:0,b.emoji||"🙂",hash,salt).run()}catch(e){return json({error:"이미 등록된 이름이거나 저장할 수 없습니다."},409)}return json({member:{id:memberId,name:b.name,role:b.role,isAdmin:b.role==="parent",emoji:b.emoji||"🙂"}},201)}
if(url.pathname==="/api/members/password"&&req.method==="PUT"){if(!me.is_admin)return json({error:"관리자만 비밀번호를 재설정할 수 있습니다."},403);const b=await body(req);if(!b.memberId||!b.password||b.password.length<4)return json({error:"구성원과 4자 이상 새 비밀번호가 필요합니다."},400);const target=await env.DB.prepare("SELECT id,family_id,role FROM members WHERE id=? AND family_id=?").bind(b.memberId,me.family_id).first();if(!target)return json({error:"가족 구성원을 찾을 수 없습니다."},404);if(target.id===me.id)return json({error:"본인 비밀번호 변경은 별도 절차를 이용해주세요."},400);const salt=id(),hash=await passwordHash(b.password,salt);await env.DB.batch([env.DB.prepare("UPDATE members SET password_hash=?,password_salt=? WHERE id=?").bind(hash,salt,target.id),env.DB.prepare("DELETE FROM sessions WHERE member_id=?").bind(target.id)]);return json({ok:true})}
if(url.pathname==="/api/account"&&req.method==="PUT"){const b=await body(req);const fields=[];if(b.name!==undefined){const name=String(b.name||"").trim();if(!name)return json({error:"이름을 입력해주세요."},400);try{await env.DB.prepare("UPDATE members SET name=? WHERE id=? AND family_id=?").bind(name,me.id,me.family_id).run()}catch(e){return json({error:"이미 사용 중인 이름입니다."},409)}}if(b.emoji!==undefined){const emoji=String(b.emoji||"").trim();if(!emoji)return json({error:"아이콘을 입력해주세요."},400);await env.DB.prepare("UPDATE members SET emoji=? WHERE id=? AND family_id=?").bind(emoji,me.id,me.family_id).run()}if(b.password!==undefined){if(String(b.password).length<4)return json({error:"새 비밀번호는 4자 이상이어야 합니다."},400);const salt=id(),hash=await passwordHash(String(b.password),salt);if(me.role==="child"){await env.DB.prepare("UPDATE password_change_requests SET status='rejected',reviewed_at=CURRENT_TIMESTAMP WHERE member_id=? AND status='pending'").bind(me.id).run();await env.DB.prepare("INSERT INTO password_change_requests(id,family_id,member_id,password_hash,password_salt) VALUES(?,?,?,?,?)").bind(id(),me.family_id,me.id,hash,salt).run();return json({ok:true,pendingApproval:true,message:"부모님께 비밀번호 변경 승인을 요청했어요."})}await env.DB.prepare("UPDATE members SET password_hash=?,password_salt=? WHERE id=?").bind(hash,salt,me.id).run();await env.DB.prepare("DELETE FROM sessions WHERE member_id=? AND token_hash<>?").bind(me.id,await digest((req.headers.get("authorization")||"").replace(/^Bearer\s+/i,""))).run()}const updated=await env.DB.prepare("SELECT id,name,role,is_admin,emoji FROM members WHERE id=?").bind(me.id).first();return json({ok:true,member:{id:updated.id,name:updated.name,role:updated.role,isAdmin:!!updated.is_admin,emoji:updated.emoji}})}
if(url.pathname==="/api/members/account"&&req.method==="PUT"){if(!me.is_admin)return json({error:"관리자만 가족 계정을 변경할 수 있습니다."},403);const b=await body(req);if(!b.memberId)return json({error:"구성원을 선택해주세요."},400);const target=await env.DB.prepare("SELECT id FROM members WHERE id=? AND family_id=?").bind(b.memberId,me.family_id).first();if(!target)return json({error:"가족 구성원을 찾을 수 없습니다."},404);if(b.name!==undefined){const name=String(b.name||"").trim();if(!name)return json({error:"이름을 입력해주세요."},400);try{await env.DB.prepare("UPDATE members SET name=? WHERE id=?").bind(name,target.id).run()}catch(e){return json({error:"이미 사용 중인 이름입니다."},409)}}if(b.emoji!==undefined){const emoji=String(b.emoji||"").trim();if(!emoji)return json({error:"아이콘을 입력해주세요."},400);await env.DB.prepare("UPDATE members SET emoji=? WHERE id=?").bind(emoji,target.id).run()}if(b.password!==undefined){if(String(b.password).length<4)return json({error:"새 비밀번호는 4자 이상이어야 합니다."},400);const salt=id(),hash=await passwordHash(String(b.password),salt);await env.DB.prepare("UPDATE members SET password_hash=?,password_salt=? WHERE id=?").bind(hash,salt,target.id).run();await env.DB.prepare("DELETE FROM sessions WHERE member_id=?").bind(target.id).run()}return json({ok:true})}
if(url.pathname==="/api/password-requests"&&req.method==="GET"){if(!me.is_admin)return json({error:"관리자만 승인 요청을 확인할 수 있습니다."},403);const rows=await env.DB.prepare(`SELECT r.id,r.member_id,m.name,m.emoji,r.created_at FROM password_change_requests r JOIN members m ON m.id=r.member_id WHERE r.family_id=? AND r.status='pending' ORDER BY r.created_at`).bind(me.family_id).all();return json({requests:rows.results||[]})}
if(url.pathname==="/api/password-requests/review"&&req.method==="POST"){if(!me.is_admin)return json({error:"관리자만 승인할 수 있습니다."},403);const b=await body(req);if(!b.requestId||!["approve","reject"].includes(b.action))return json({error:"승인 요청과 처리 방법을 확인해주세요."},400);const r=await env.DB.prepare("SELECT * FROM password_change_requests WHERE id=? AND family_id=? AND status='pending'").bind(b.requestId,me.family_id).first();if(!r)return json({error:"처리할 승인 요청이 없습니다."},404);if(b.action==="approve"){await env.DB.batch([env.DB.prepare("UPDATE members SET password_hash=?,password_salt=? WHERE id=?").bind(r.password_hash,r.password_salt,r.member_id),env.DB.prepare("DELETE FROM sessions WHERE member_id=?").bind(r.member_id),env.DB.prepare("UPDATE password_change_requests SET status='approved',reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?").bind(me.id,r.id)])}else await env.DB.prepare("UPDATE password_change_requests SET status='rejected',reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?").bind(me.id,r.id).run();return json({ok:true,approved:b.action==="approve"})}
if(url.pathname==="/api/state"&&req.method==="GET"){const rows=await env.DB.prepare("SELECT state_key,value_json,updated_at FROM family_state WHERE family_id=?").bind(me.family_id).all();const state={};for(const r of rows.results||[]){try{state[r.state_key]=JSON.parse(r.value_json)}catch{}}return json({state})}
if(url.pathname==="/api/state"&&req.method==="PUT"){const b=await body(req),allowed=new Set(["daily_schedules","family_schedules","monthly_memos","event","memories","member_albums","profile_photos","allowance_ledger","allowance_audit","household_ledger"]);if(!allowed.has(b.key))return json({error:"지원하지 않는 데이터 종류입니다."},400);await env.DB.prepare(`INSERT INTO family_state(family_id,state_key,value_json,updated_at,updated_by) VALUES(?,?,?,CURRENT_TIMESTAMP,?) ON CONFLICT(family_id,state_key) DO UPDATE SET value_json=excluded.value_json,updated_at=CURRENT_TIMESTAMP,updated_by=excluded.updated_by`).bind(me.family_id,b.key,JSON.stringify(b.value??null),me.id).run();return json({ok:true})}
return json({error:"Not found"},404)}};